<form action="addCategory" method="POST">

    <div class="row">
        <label for="nombre">Nombre</label>
        <input type="text" id="nombre" name="nombre" placeholder="Nombre" required>

        <label for="descripcion">Descripcion</label>
        <input type="text" id="descripcion" name="descripcion" placeholder="Descripcion" required>

        <label for="responsable">Responsable</label>
        <input type="text" id="responsable" name="responsable" placeholder="Responsable" required>

    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>