<?php require './templates/layout/header.phtml' ?>

<h4>CATEGORIAS</h4>

<?php if ($this->session) : require $form; endif ?>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Responsable</th>
            <?php if ($this->session) : ?>
                <th>Acciones</th>
            <?php endif; ?>

        </tr>
    </thead>

    <tbody>
        <?php foreach ($categories as $category) : ?>
            <tr>
                <td><a href="categories/<?= $category->id ?>"><?= $category->nombre ?></a></td>
                <td><?= $category->descripcion ?></td>
                <td><?= $category->responsable ?></td>

                <?php if ($this->session) : ?>
                    <td>
                        <a href="editCategoryForm/<?= $category->id ?>" class="btn btn-primary">Editar</a>
                        <a href="removeCategory/<?= $category->id ?>" class="btn btn-danger"
                            onclick="return confirm('¿Estás seguro de que queres borrar esta categoria?');">Borrar</a>
                    </td>
                <?php endif ?>
            </tr>

        <?php endforeach ?>
    </tbody>

</table>

<?php require './templates/layout/footer.phtml' ?>