<form action="addItem" method="POST">

    <div class="row">

        <label>De que categoria es</label>
        <select required name="id_categoria" class="form-control">
            <option selected disabled>Seleccione la categoria</option>
            <?php foreach ($categories as $category) : ?>
                <option value="<?= $category->id ?>"><?= $category->nombre ?></option>
            <?php endforeach ?>
        </select>

        <label>Nombre</label>
        <input required name="nombre" type="text" placeholder="Ingrese el nombre" class="form-control"></input>

        <label>Material</label>
        <input required name="material" type="text" placeholder="Ingrese material" class="form-control"></input>
    
        <label>Precio</label>
        <input  required name="precio" type="number" placeholder="precio" class="form-control" ></input>
                
        <label>Disponible</label>
        <input  required name="disponible" type="boolean" placeholder="disponible" class="form-control" ></input>

    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>