<?php require './templates/layout/header.phtml' ?>

<h4>Prenda</h4>

<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <h5>Premda</h5>
            <p>Categoria: <a href="categoria/<?= $item->id ?>"><?= $item->id ?></a></p>
            <p>Material: <?= $item->material ?></p>
            <p>Precio: <?= $item->precio ?></p>
            <p>Disponible: <?= $item->disponible ?></p>
        </div>
    </li>
</ul>

<?php require './templates/layout/footer.phtml' ?>