<?php require './templates/layout/header.phtml' ?>

<h4>Prenda</h4>

<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <h5>Prenda</h5>
            <p>Categoria: <?= $item->categoriaNombre ?></p>
            <p>Material: <?= $item->prendaMaterial ?></p>
            <p>Precio: <?= $item->prendaPrecio ?></p>
            <p>Disponible: <?= $item->prendaDisponible ?></p>
        </div>
    </li>
</ul>

<?php require './templates/layout/footer.phtml' ?>